/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  /**
   * Surface height in xComponent.
   */
  public static readonly X_COMPONENT_SURFACE_HEIGHT = 1920;

  /**
   * Surface width in xComponent.
   */
  public static readonly X_COMPONENT_SURFACE_WIDTH = 1080;

  /**
   * Border width in xComponent.
   */
  public static readonly X_COMPONENT_BORDER_WIDTH = 0.5;

  /**
   * Border width in capture button.
   */
  public static readonly CAPTURE_BUTTON_BORDER_WIDTH = 3;

  /**
   * Border radius size in capture button.
   */
  public static readonly CAPTURE_BUTTON_BORDER_RADIUS = 70;

  /**
   * Margins of the component.
   */
  public static readonly CAPTURE_BUTTON_COLUMN_MARGIN = 24;

  /**
   * paddings of the component.
   */
  public static readonly CAPTURE_BUTTON_COLUMN_PADDING = 24;

  /**
   * size of the back icon.
   */
  public static readonly BACK_ICON_SIZE = 24;

  /**
   * size of the back icon.
   */
  public static readonly IMAGE_SIZE = 25;

  /**
   * Margins of the back icon.
   */
  public static readonly BACK_ICON_MARGIN = 24;

  /**
   * The full percentage of component.
   */
  public static readonly FULL_PERCENT: string = '100%';

  /**
   * The Eighty-five percent of component.
   */
  public static readonly EIGHTY_FIVE_PERCENT: string = '85%';

  /**
   * The Eighty percent of component.
   */
  public static readonly EIGHTY_PERCENT: string = '80%';

  /**
   * The seventy-five percent of the components.
   */
  public static readonly SEVENTY_FIVE_PERCENT: string = '75%';

  /**
   * The seventy percent of the components.
   */
  public static readonly SEVENTY_PERCENT: string = '70%';

  /**
   * The forty percent of the components.
   */
  public static readonly FORTY_PERCENT: string = '40%';

  /**
   * The thirty percent of the components.
   */
  public static readonly THIRTY_PERCENT: string = '30%';

  /**
   * The fifteen percent of the bottom of the margin.
   */
  public static readonly FIFTEEN_PERCENT: string = '15%';

  /**
   * The ten percent of the bottom of the margin.
   */
  public static readonly TEN_PERCENT: string = '10%';

  /**
   * The zero percent of the bottom of the margin.
   */
  public static readonly ZERO_PERCENT: string = '0%';

  /**
   * border radius.
   */
  public static readonly TEXT_BORDER_RADIUS: number = 25;

  /**
   * font size.
   */
  public static readonly FONT_SIZE_14: number = 14;

  /**
   * column space.
   */
  public static readonly COLUMN_SPACE_24: number = 24;

  /**
   * row space.
   */
  public static readonly ROW_SPACE_24: number = 24;

  /**
   * default zoom ratio.
   */
  public static readonly DEFAULT_ZOOM_RATIO: number = 1;

  /**
   * border radius.
   */
  public static readonly BORDER_RADIUS_14: number = 14;

  /**
   * capture Column width.
   */
  public static readonly CAPTURE_COLUMN_WIDTH: number = 50;

  /**
   * capture Column width.
   */
  public static readonly CAPTURE_ROW_HEIGHT: number = 28;

  /**
   * AUDIO_BITRATE.
   */
  public static readonly AUDIO_BITRATE: number = 48000;

  /**
   * AUDIO_CHANNELS.
   */
  public static readonly AUDIO_CHANNELS: number = 2;

  /**
   * AUDIO_SAMPLE_RATE.
   */
  public static readonly AUDIO_SAMPLE_RATE: number = 48000;

  /**
   * VIDEO_BITRATE.
   */
  public static readonly VIDEO_BITRATE: number = 8000000;

  /**
   * VIDEO_FRAME.
   */
  public static readonly MAX_VIDEO_FRAME: number = 60;

  /**
   * edit page.
   */
  public static readonly EDIT_PAGE_NAME = 'EditPage';
};