/*
* Copyright (c) 2025 Huawei Device Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
// [Start monitor_decorator_object_trace_observed_v2]
import { hilog } from '@kit.PerformanceAnalysisKit';

@ObservedV2
class Inner {
  @Trace public num: number = 0;
}

@ObservedV2
class Outer {
  public inner: Inner = new Inner();

  @Monitor('inner.num')
  onChange(monitor: IMonitor) {
    hilog.info(0xFF00, 'testTag', '%{public}s',
      `inner.num change from ${monitor.value()?.before} to ${monitor.value()?.now}`);
  }
}

@Entry
@ComponentV2
struct Index {
  outer: Outer = new Outer();

  build() {
    Column() {
      Button('change num')
        .onClick(() => {
          this.outer.inner.num = 100; // 能够触发onChange方法
        })
    }
  }
}
// [End monitor_decorator_object_trace_observed_v2]
@Component
export struct MonitorDecoratorObjectTraceObservedV2 {
  @State egLanes: LengthConstrain = { minLength: 200, maxLength: 300 };
  @Consume pathStack: NavPathStack;

  build() {
    NavDestination() {
      Index()
    }
    .backgroundColor('#f1f2f3')
    .title($r('app.string.monitor_decorator_object_trace_observed_v2'))
  }
}