/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  // 用于列表中图片总数
  public static readonly IMAGE_TOTAL_NUM: number = 100;
  // 用于Flex中Text总数
  public static readonly TEXT_TOTAL_NUM: number = 200;
  // 用于text数字循环取模
  public static readonly TEXT_CONTENT_DIVIDER: number = 10;
}