/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { router, Router } from '@kit.ArkUI'

@Entry
@Component
struct Index {
build() {
 Column(){
   Column(){
     // 请将$r('app.string.Interface_Layout_Border_Settings')替换为实际资源文件，在本示例中该资源文件的value值为"点击界面布局和边框设置"
     Text($r('app.string.Interface_Layout_Border_Settings')).backgroundColor(Color.Green)
   }.width('100%').height(50)
   .onClick(()=>{
     router.pushUrl({url:'homePage/InterfaceLayoutBorderSettings'});
   })
   Column(){
     // 请将$r('app.string.Customize_Canvas_Component_Drawing')替换为实际资源文件，在本示例中该资源文件的value值为"点击自定义绘制Canvas组件"
     Text($r('app.string.Customize_Canvas_Component_Drawing')).backgroundColor(Color.Green)
   }.width('100%').height(50)
   .onClick(()=>{
     router.pushUrl({url:'homePage/CustomizeCanvasComponentDrawing'});
   })
 }
}
}