/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { hilog } from '@kit.PerformanceAnalysisKit';
import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect } from '@ohos/hypium';
import { abilityDelegatorRegistry, Driver, ON } from '@kit.TestKit';
import { Want } from '@kit.AbilityKit';

const TAG: string = 'ProcessModel';
const DOMAIN_NUMBER: number = 0xFF00;
const delegator: abilityDelegatorRegistry.AbilityDelegator = abilityDelegatorRegistry.getAbilityDelegator();
const bundleName = abilityDelegatorRegistry.getArguments().bundleName;

export default function abilityTest() {
  describe('ActsAbilityTest', () => {
    // Defines a test suite. Two parameters are supported: test suite name and test suite function.
    beforeAll(async (done: Function) => {
      // Presets an action, which is performed only once before all test cases of the test suite start.
      // This API supports only one parameter: preset action function.
      hilog.info(DOMAIN_NUMBER, TAG, 'ActsAbilityTest begin');
      const want: Want = {
        bundleName: bundleName,
        abilityName: 'EntryAbility'
      };
      await delegator.startAbility(want);
      const driver = Driver.create();
      await driver.delayMs(1000);
      hilog.info(DOMAIN_NUMBER, TAG, 'get top ability');
      await driver.delayMs(1000);

      done();
    })
    beforeEach(() => {
      // Presets an action, which is performed before each unit test case starts.
      // The number of execution times is the same as the number of test cases defined by **it**.
      // This API supports only one parameter: preset action function.
    })
    afterEach(async (done: Function) => {
      // Presets a clear action, which is performed after each unit test case ends.
      // The number of execution times is the same as the number of test cases defined by **it**.
      // This API supports only one parameter: clear action function.
      const driver = Driver.create();
      await driver.pressBack();
      await driver.delayMs(2000);
      done();
    })
    afterAll(() => {
      // Presets a clear action, which is performed after all test cases of the test suite end.
      // This API supports only one parameter: clear action function.
    })
    /**
     * @tc.number test_Subscription_001
     * @tc.name test_Subscription_001
     * @tc.desc 测试动态订阅公共事件中创建订阅者示例
     * @tc.level: Level 1
     */
    it('test_Subscription_001', 1, async (done: Function) => {
      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_001 begin');
      const driver = Driver.create();

      const button = await driver.findComponent(ON.text('CreatSubscribeInfo'));
      await button.click();
      await driver.delayMs(2000);
      let event: string = await AppStorage.get('event')!;
      expect(event).assertEqual('CreateSubscriberCallback');
      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_001 end');
      done();
    })

    /**
     * @tc.number test_Subscription_002
     * @tc.name test_Subscription_002
     * @tc.desc 测试动态订阅公共事件中创建订阅回调函数示例
     * @tc.level: Level 1
     */
    it('test_Subscription_002', 1, async (done: Function) => {
      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_002 begin');
      const driver = Driver.create();

      const button = await driver.findComponent(ON.text('CreatSubscribeInfo'));
      await button.click();
      await driver.delayMs(2000);

      const button1 = await driver.findComponent(ON.text('订阅公共事件'));
      await button1.click();
      await driver.delayMs(100);

      let event: string = await AppStorage.get('event')!;
      expect(event).assertEqual('SubscribeToPublicEventsSuccess');

      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_002 end');
      done();
    })

    /**
     * @tc.number test_Subscription_003
     * @tc.name test_Subscription_003
     * @tc.desc 测试调用CommonEvent中的unsubscribe()方法取消订阅某事件示例
     * @tc.level: Level 1
     */
    it('test_Subscription_003', 1, async (done: Function) => {
      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_003 begin');
      const driver = Driver.create();

      const button = await driver.findComponent(ON.text('CreatSubscribeInfo'));
      await button.click();
      await driver.delayMs(2000);

      const button1 = await driver.findComponent(ON.text('取消订阅订阅公共事件'));
      await button1.click();
      await driver.delayMs(100);

      let event: string = await AppStorage.get('event')!;
      expect(event).assertEqual('UnsubscribePublicEvents');

      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_003 end');
      done();
    })

    /**
     * @tc.number test_Subscription_004
     * @tc.name test_Subscription_004
     * @tc.desc 测试发布不携带信息的公共事件示例
     * @tc.level: Level 1
     */
    it('test_Subscription_004', 1, async (done: Function) => {
      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_004 begin');
      const driver = Driver.create();

      const button = await driver.findComponent(ON.text('CreatSubscribeInfo'));
      await button.click();
      await driver.delayMs(2000);

      const button1 = await driver.findComponent(ON.text('发布不携带信息的公共事件\'event\''));
      await button1.click();
      await driver.delayMs(100);

      let event: string = await AppStorage.get('event')!;
      expect(event).assertEqual('PublicEventNoInformation');

      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_004 end');
      done();
    })

    /**
     * @tc.number test_Subscription_005
     * @tc.name test_Subscription_005
     * @tc.desc 测试发布携带信息的公共事件示例
     * @tc.level: Level 1
     */
    it('test_Subscription_005', 1, async (done: Function) => {
      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_005 begin');
      const driver = Driver.create();

      const button = await driver.findComponent(ON.text('CreatSubscribeInfo'));
      await button.click();
      await driver.delayMs(2000);

      const button1 = await driver.findComponent(ON.text('发布携带信息的公共事件\'event\''));
      await button1.click();
      await driver.delayMs(100);

      let event: string = await AppStorage.get('event')!;
      expect(event).assertEqual('PublicEventCarryingInformation');

      hilog.info(DOMAIN_NUMBER, TAG, 'test_Subscription_005 end');
      done();
    })
  })
}