/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// [Start startup_entryconfig]
// [Start startup_config]
import { StartupConfig, StartupConfigEntry, StartupListener, Want } from '@kit.AbilityKit';
// [StartExclude startup_config]
import { hilog } from '@kit.PerformanceAnalysisKit';
import { BusinessError } from '@kit.BasicServicesKit';
// [EndExclude startup_config]

export default class MyStartupConfigEntry extends StartupConfigEntry {
  // [StartExclude startup_config]
  onConfig() {
    hilog.info(0x0000, 'testTag', `onConfig`);
    let onCompletedCallback = (error: BusinessError<void>) => {
      hilog.info(0x0000, 'testTag', `onCompletedCallback`);
      if (error) {
        hilog.error(0x0000, 'testTag', 'onCompletedCallback: %{public}d, message: %{public}s', error.code,
          error.message);
      } else {
        hilog.info(0x0000, 'testTag', `onCompletedCallback: success.`);
      }
    };
    let startupListener: StartupListener = {
      'onCompleted': onCompletedCallback
    };
    let config: StartupConfig = {
      'timeoutMs': 10000,
      'startupListener': startupListener
    };
    return config;
  }
  // [EndExclude startup_config]
  // [StartExclude startup_entryconfig]
  onRequestCustomMatchRule(want: Want): string {
    if (want?.parameters?.fromType == 'card') {
      return 'ruleCard';
    }
    return '';
  }
  // [EndExclude startup_entryconfig]
}
// [End startup_config]
// [End startup_entryconfig]