/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonEventValue {

  public static EVENT_DISABLE_WIFI = 'event_disable_wifi';

  public static EVENT_ENABLE_WIFI = 'event_enable_wifi';

  public static EVENT_QUERY_WIFI_STATUS = 'event_query_wifi_status';

  public static EVENT_DISABLE_ADMIN = 'event_disable_admin';

  public static EVENT_REBOOT = 'event_reboot';

  public static EVENT_RESULT = 'event_result';

  public static STATUS_ACTIVE = 0x001;

  public static STATUS_WIFI = 0x002;

  public static STATUS_RESULT = 0x003;
}