/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// [Start FormEditDemo_EntryFormEditAbility]
// entry/src/main/ets/entryformeditability/EntryFormEditAbility.ets
import { FormEditExtensionAbility } from '@kit.FormKit';
import { Want, UIExtensionContentSession } from '@kit.AbilityKit';
import { ExtensionEvent } from '../model/ExtensionEvent';
import { hilog } from '@kit.PerformanceAnalysisKit';

const TAG: string = 'FormEditDemo[EntryFormEditAbility] -->';
let storage: LocalStorage = ExtensionEvent.getStorage();
const DOMAIN = 0xFF00;

export default class EntryFormEditAbility extends FormEditExtensionAbility {

  onCreate() {
    hilog.info(DOMAIN, TAG, `${TAG} onCreate`);
  }
  onForeground(): void {
    hilog.info(DOMAIN, TAG, `${TAG} EntryFormEditAbility onForeground.....`);
  }
  onBackground(): void {
    hilog.info(DOMAIN, TAG, `${TAG} EntryFormEditAbility onBackground......`);
  }
  onDestroy(): void {
    hilog.info(DOMAIN, TAG, `${TAG} EntryFormEditAbility onDestroy......`);
  }
  onSessionCreate(want: Want, session: UIExtensionContentSession) {
    hilog.info(DOMAIN, TAG, `${TAG} onSessionCreate start..... want: ${JSON.stringify(want)}`);
    // 获取被编辑卡片的卡片ID
    const formId: string | undefined = want.parameters?.cardId as string;
    // 获取预览卡片的卡片ID
    const previewFormId: string | undefined = want.parameters?.previewCardId as string;

    if (formId) {
      hilog.info(DOMAIN, TAG, `${TAG} form id is ${formId}`);
      storage.setOrCreate('formId', formId);
    }
    if (previewFormId) {
      hilog.info(DOMAIN, TAG, `${TAG} preview form id is ${previewFormId}`);
      storage.setOrCreate('previewFormId', previewFormId);
    }
    let extensionEvent: ExtensionEvent = new ExtensionEvent();
    extensionEvent.setStartSecondPage((): void => this.startSecondPage());
    storage.setOrCreate('extensionEvent', extensionEvent);
    storage.setOrCreate('context', this.context);
    try {
      session.loadContent('pages/FormEditExtension', storage);
    } catch (e) {
      hilog.error(DOMAIN, TAG, `${TAG} EntryFormEditAbility loadContent err, want: ${JSON.stringify(e)}`);
    }
  }
  onSessionDestroy(session: UIExtensionContentSession) {
    hilog.info(DOMAIN, TAG, `${TAG} onSessionDestroy`);
  }
  private startSecondPage() {
    const bundleName: string = this.context.extensionAbilityInfo.bundleName;
    const secPageAbilityName: string = 'FormEditSecPageAbility';
    hilog.info(DOMAIN, TAG, `${TAG} startSecondPage. bundleName: ${bundleName}, secPageAbilityName: ${secPageAbilityName}.`);
    try {
      // 拉起二级编辑页
      this.context.startSecondPage({
        bundleName: bundleName,
        parameters: {
          'secPageAbilityName': secPageAbilityName
        }
      })
      hilog.info(DOMAIN, TAG, `${TAG} startSecondPage success!`);
    } catch (err) {
      hilog.error(DOMAIN, TAG, `${TAG} startSecondPage failed, err: ${JSON.stringify(err)}`);
    }
  }
};
// [End FormEditDemo_EntryFormEditAbility]